### ISSUE TITLE
Video Import Script

### ISSUE THREAD

**Issue by dirkkelly** [breadtubetv/breadtubetv#36]
## Story

Given I am a Developer
And I want to import a new video
When I execute `bin/video import VIDEOID`
Then the video metadata* is added to `data/videos.yml`

### Video MetaData

```
VIDEO_ID:
  id: VIDEO_ID
  title: VIDEO_TITLE.split(" | ").first
  channel: VIDEO_CHANNEL_SLUG
  series: VIDEO_TITLE.split(" | ").last
  description: VIDEO_DESCRIPTION.paragraphs.first
  source: youtube

```
