### ISSUE TITLE
Feature hot /r/breadtube posts?

### ISSUE THREAD

**Issue by soliveira-vouga** [breadtubetv/breadtubetv#67]
What do you all think about adding a section that features the hot /r/breadtube posts? Does it make sense to include it on the site? 

I've created a little script that fetches the 20 hot posts from /r/breadtube and stores it in a yaml file. You can check it out in https://github.com/breadtubetv/scripts

Another question: Do we need that other repo or do we want to make this repo a monorepo and just store all of our scripts here?

I'm not too familiar with Netlify so I'm not sure how best to work with it in terms of repo organization.

For example, I can make that /r/breadtube script run as a lambda function but I'm not sure how this would be done with Netlify nor how we can have that data be used by the main site.

Another example would be a script that periodically updates the subscription numbers and we can store that in a separate yaml file that would be an array of channels with each item containing the slug and # of subscriptions.

**Comment by soliveira-vouga** [comment]
Example of Yaml file produced:

```yaml
posts:
  - title: "One year ago today, Contrapoints released “Autogynephilia.” Not only is her video refuting Blanchard’s taxonomy moving and insightful, but one of Natalie’s best videos to date."
    author: "AsterismAlex"
    url: "https://youtu.be/6czRFLs5JQo"
    permalink: "/r/BreadTube/comments/am2o3e/one_year_ago_today_contrapoints_released/"
    thumbnail: "https://a.thumbs.redditmedia.com/TG9SVTVgsjLQOgeHNphDxSSK5mcWZkTow0iQCpHb_N4.jpg"
    score: 77
  - title: "Is the US Meddling in Venezuela? Max Blumenthal Asks US Congress Members"
    author: "TissueBoxesOfFun"
    url: "https://youtu.be/BrapYLtkBhY"
    permalink: "/r/BreadTube/comments/am30jr/is_the_us_meddling_in_venezuela_max_blumenthal/"
    thumbnail: "https://b.thumbs.redditmedia.com/C7dumT7NjZWRsXfFFSy3EqO9CeLR0c_tu5_ybjK-Jmg.jpg"
    score: 25
  - title: "Kamala Harris Mocks People Who Say We Need To 'Build More Schools, Less Jails'"
    author: "RicknMorty93"
    url: "https://www.youtube.com/watch?v=4HZjLnj7WGM"
    permalink: "/r/BreadTube/comments/altdvt/kamala_harris_mocks_people_who_say_we_need_to/"
    thumbnail: "https://b.thumbs.redditmedia.com/e7zoaTgRsE3JZ5xSfLF8v_1npNlHAEExg6BDT6fEM7w.jpg"
    score: 609
  - title: "Don't Talk to the Police | Regent University School of Law"
    author: "JumpJax"
    url: "https://www.youtube.com/watch?v=d-7o9xYp7eE"
    permalink: "/r/BreadTube/comments/alzqxs/dont_talk_to_the_police_regent_university_school/"
    thumbnail: "https://b.thumbs.redditmedia.com/NmOdN7p_hswdKh3K1CvLD_cuNj56HI94MoL3Tpn1U3k.jpg"
    score: 59
  - title: "Anti-Gay Bigot Kim Davis Will Have To Pay The Legal Fees Of The Gay People Who Sued Her"
    author: "FannyKaplansBullet"
    url: "https://www.youtube.com/watch?v=r2rvQKlf6M8"
    permalink: "/r/BreadTube/comments/alz6gt/antigay_bigot_kim_davis_will_have_to_pay_the/"
    thumbnail: "https://b.thumbs.redditmedia.com/CejqTjGD2nBQ4f-9O1s2sL9I-j9ADpkTDPc_Dqzj7-c.jpg"
    score: 60
  - title: "Independence Day vs. War of the Worlds | Lindsay Ellis"
    author: "Nekoroboticon"
    url: "https://www.youtube.com/watch?v=KioF1sTQFtE"
    permalink: "/r/BreadTube/comments/alxj0n/independence_day_vs_war_of_the_worlds_lindsay/"
    thumbnail: "https://a.thumbs.redditmedia.com/JcqzinjiyYbpwYJaayO93XS1hsXaRLdP_kZjv_Lj674.jpg"
    score: 103
  - title: "[German] Analysis on how German far-right Youtuber \"Der Volkslehrer\" portrays himself as a victim"
    author: "King_Jules"
    url: "https://youtu.be/B7uP_C8_Taw"
    permalink: "/r/BreadTube/comments/am2k6m/german_analysis_on_how_german_farright_youtuber/"
    thumbnail: "https://b.thumbs.redditmedia.com/kn2jT3AiwnQFcmwkx-6im5xuMo7NYrswzppDn8UbyCc.jpg"
    score: 7
  - title: "Politics in the Age of YouTube at Imperial College Labour Society. Had a lot of fun chairing this panel - hope you all enjoy it too!"
    author: "blazar23"
    url: "https://youtu.be/YtgnPzb4KlA"
    permalink: "/r/BreadTube/comments/alr0tf/politics_in_the_age_of_youtube_at_imperial/"
    thumbnail: "https://b.thumbs.redditmedia.com/9vQ2vVExxkyF2LVfY9tIJNjU9MozK6DUfhU27XztyHI.jpg"
    score: 475
  - title: "Wii Shop - A 90’s Nintendo Capitalism Montage"
    author: "cjf_colluns"
    url: "https://youtu.be/vFDnByRhHoM"
    permalink: "/r/BreadTube/comments/am4dl7/wii_shop_a_90s_nintendo_capitalism_montage/"
    thumbnail: "https://b.thumbs.redditmedia.com/6iuN3U3_Xm4ibEs9wSUV1qxYAvCP1GQxY846zjSDM4Q.jpg"
    score: 5
  - title: "MSNBC Guest: 'Centrism' Defends The Rich"
    author: "basscorruption"
    url: "https://www.youtube.com/watch?v=yL2Art5_VpA"
    permalink: "/r/BreadTube/comments/altxxw/msnbc_guest_centrism_defends_the_rich/"
    thumbnail: "https://a.thumbs.redditmedia.com/yRctakfq0Kb-xbNSyAUZ0lsk0TvcaUc_SGER2lammj4.jpg"
    score: 162
  - title: "Broken Reality, Vaporwave, and Irony | Errant Signal"
    author: "Ootachiful"
    url: "https://www.youtube.com/watch?v=EtaHmaEAbi4"
    permalink: "/r/BreadTube/comments/am4wut/broken_reality_vaporwave_and_irony_errant_signal/"
    thumbnail: "https://b.thumbs.redditmedia.com/D3akxl6KKS0D7ioqEYdRKwY146jYCj_G0WQh5owO6PQ.jpg"
    score: 4
  - title: "Politics In The Age Of YouTube: Imperial College Talk 2019"
    author: "YuriRedFox6969"
    url: "https://www.youtube.com/watch?v=YtgnPzb4KlA"
    permalink: "/r/BreadTube/comments/am3l09/politics_in_the_age_of_youtube_imperial_college/"
    thumbnail: "https://b.thumbs.redditmedia.com/3HMA7HSmzblz8GiicNBxzIJAkU9M4U773fvB3TwKyAY.jpg"
    score: 4
  - title: "A Novara Explainer on the Four Day Working Week."
    author: "tyskysour"
    url: "https://www.youtube.com/watch?v=qHhF3_FD0iU"
    permalink: "/r/BreadTube/comments/am0z4s/a_novara_explainer_on_the_four_day_working_week/"
    thumbnail: "https://a.thumbs.redditmedia.com/Twcv6GFGc1aTgosVe_qUqP8PNmLx95nV1yDJk23AA24.jpg"
    score: 10
  - title: "Hashtag ACAB | Sheep In The Box"
    author: "SheepInTheBox26"
    url: "https://www.youtube.com/watch?v=VQUuizWTDjY"
    permalink: "/r/BreadTube/comments/am327l/hashtag_acab_sheep_in_the_box/"
    thumbnail: "https://b.thumbs.redditmedia.com/cXw46LXLHZNEkWhy4_u2JPZIRj4M1MeeBXRn10HN6LI.jpg"
    score: 4
  - title: "Should the U.S intervene in Venezuela?"
    author: "MangoTangoBandingo"
    url: "https://www.youtube.com/watch?v=8EQurNpUSeU"
    permalink: "/r/BreadTube/comments/am1fcs/should_the_us_intervene_in_venezuela/"
    thumbnail: "https://b.thumbs.redditmedia.com/GiU-iDWVEhaY9a4YL6RB8ri4lg8FUoyG4EUrusdflpk.jpg"
    score: 8
  - title: "Ben Shapiro Says Kamala Harris Is A \"Radical\" Like Bernie Sanders &amp; AOC"
    author: "FannyKaplansBullet"
    url: "https://www.youtube.com/watch?v=UeuMMtwvHw4"
    permalink: "/r/BreadTube/comments/alz7iy/ben_shapiro_says_kamala_harris_is_a_radical_like/"
    thumbnail: "https://b.thumbs.redditmedia.com/GqU5NT750_Lbp7aGI4t0L3lOlJCR4rFy-4PJyiKV9kU.jpg"
    score: 18
  - title: "Graham Linehan's Anti-Trans Bigotry - A Critical Response | EssenceOfThought [32:10]"
    author: "PostColFem"
    url: "https://www.youtube.com/watch?v=rcH1zqwjuSM"
    permalink: "/r/BreadTube/comments/am4jc0/graham_linehans_antitrans_bigotry_a_critical/"
    thumbnail: "https://b.thumbs.redditmedia.com/SH63lyhkrIIajq5geZjIiAIwHlXaokyH9fYebrqeVtQ.jpg"
    score: 3
  - title: "What Is Happening to Alex Jones?"
    author: "FannyKaplansBullet"
    url: "https://www.youtube.com/watch?v=CoPSUL6UDt0"
    permalink: "/r/BreadTube/comments/alzfov/what_is_happening_to_alex_jones/"
    thumbnail: "https://b.thumbs.redditmedia.com/l9Qf1HiO0nRLAW6HvPCRQ5OHp6wc7rjC51RXFl6kDVM.jpg"
    score: 13
  - title: "Why It Didn't Work - Dakaichi ~I'm Being Harassed by the Sexiest Man of the Year~ (anime analysis)"
    author: "Daveed93"
    url: "https://www.youtube.com/watch?v=8xCWdIIEFIQ"
    permalink: "/r/BreadTube/comments/am2yzt/why_it_didnt_work_dakaichi_im_being_harassed_by/"
    thumbnail: "https://a.thumbs.redditmedia.com/EAs2iZYay1HibjmNGDS-ZyV-9u8-i1ET5tCQlqi5_k8.jpg"
    score: 3
```

**Comment by dirkkelly** [comment]
Looking at this now, thanks!

**Comment by dirkkelly** [comment]
Thanks for putting this together, I do think this can go into https://github.com/breadtubetv/breadtubetv/ under `scripts/`

We'll need to make some modifications to the output also to match the data structures

## `/data/videos.yml`

First we need to add these to the videos data file, I think this could just amend for now, in the future we can be smarter about updating.

```yaml
8xCWdIIEFIQ:
  id: "8xCWdIIEFIQ"
  title: "Why It Didn't Work - Dakaichi ~I'm Being Harassed by the Sexiest Man of the Year~ (anime analysis)"
  channel: "Daveed93" // this will need to match `data/channels.yml`
  permalink: "/r/BreadTube/comments/am2yzt/why_it_didnt_work_dakaichi_im_being_harassed_by/"
  thumbnail: "https://a.thumbs.redditmedia.com/EAs2iZYay1HibjmNGDS-ZyV-9u8-i1ET5tCQlqi5_k8.jpg"
  score: 3
123etc456abc:
```

## `content/playlists/hot.md`

```
---
title: r/breadtube Hottest
videos:
  - 8xCWdIIEFIQ
  - ...
---
```
