### ISSUE TITLE
Bake doesn't handle YouTube "aliases" 

### ISSUE THREAD

**Issue by j16r** [breadtubetv/breadtubetv#98]
**Describe the bug**

Bake does not correctly handle YouTube aliases, e.g: `https://www.youtube.com/dirkkelly` will return an empty channel record. It will save the empty record with an empty url and this will panic if it's read in, we don't currently handle this.

**To Reproduce**

1. Use the bake command to update the `dirkkelly` channel
2. Observe the file `bake/data/channels/dirkkelly.yml`
3. You should observe the following information:

```
description: Austramerican thinking about politics, economics, and technology during
  the people's struggle to survive the collapse of capitalism.
name: Dirk Kelly
providers:
  youtube:
    name: ""
    slug: ""
    url: null
    description: ""
    subscribers: 0
slug: dirkkelly
subscribers: 12
tags:
- breadtube
url: https://www.youtube.com/dirkkelly
```

**Expected behavior**

Should fetch the correct information for the youtube channel pointed to by the alias.
